feat(lib): rewrite utils/helper in TS
Rewrites `utils/helper.js` in TypeScript:
- Augments `App` in `@vue/runtime-core` so that `__VUE_I18N_SYMBOL_`
  introduced by `vue-i18n` may be optionally handled.
- Adds `@internal` directives in TSDoc comments. By adding `@internal`
  directives, `api-extractor` somehow failed with the following error:

    ERROR: Internal Error: Unable to analyze the export "getValueByPath" in
    /buefy/packages/buefy-next/temp-dts/utils/helpers.d.ts
    You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.

  If I removed the `@internal` scope from `getValueByPath`,
  `api-extractor` started to fail with a similar error around `mod`. The
  error disappered by removing the `@internal` scope from
  `getValueByPath` and moving `export` statements to the function
  definitions of `mod`, `bound`, and `hasFlag`.
- `toCssWidth` tweaks `isNaN(width)` as `isNaN(+width)` to avoid the
  type error caused because `isNaN` does not accept a string.
- `matchWithGroups` makes sure `pattern` contains group names, otherwise
  throws `RangeError`. It also removes a redundant check of group names
  that should never become `true`.
- Introduces a new utility type `DeepPartial` to properly type
  `mergeFn`.
- `isCustomElement` picks only the `$root` field of
  `ComponentPublicInstance`. We may face type errors if we use
  `ComponentPublicInstance` with default type parameters.
- Introduces a new interface `MultiColumnSortPriority` which represents
  the element type of the `sortingPriority` parameter of
  `multiColumnSort`. And replaces the type of `sortingPriority`:
  `string[]` → `MultiColumnSortPriority[]`.
- Introduces a new interface `TranslateTouchAsDragEventOptions` which
  represents the `options parameter of the `translateTouchAsDragEvent`
- Introduces a new type utility `ExtractComponentProps` that extracts
  the props type from a component constructor.
- Introduces a new helper type `ExtractComponentData` that extracts the
  data type from the constructor of a component. It may help us avoiding
  use of `any` when we `mount` or `shallowMount` a component that has
  mixins in tests using Vue test utils. As far as I tested, `mount` and
  `shallowMount` do not respect data fields in mixins.
- `isVueComponent` narrows the parameter `c` to
  `ComponentPublicInstance`.
- `isDefined` makes sure that the argument is not `undefined` by type
  narrowing